// app/inventory/page.tsx
import { CarCard } from "@/components/CarCard"; // Import your CarCard component

// Define your static car data
// NOTE: For better scalability, consider moving this car data to a centralized file (e.g., lib/data/cars.ts)
// and importing it here and in app/inventory/[slug]/page.tsx
const cars = [
  {
    id: "4",
    name: "NISSAN NOTE E-POWER",
    price: "1.25M",
    imageUrl: "/cars/nissannote.jpeg",
    altText: "Nissan Note E-power",
    year: "2018",
    engine: "1200cc (Hybrid)",
    mileage: "Low Mileage",
    transmission: "Automatic",
    fuelType: "Petrol",
    linkSlug: "nissan-note-e-power-2018",
    description: "Innovative hybrid technology with excellent fuel economy.",
    images: [
      "/cars/nissannote.jpeg",
      "/cars/nissannote1.jpeg",
      "/cars/nissannote2.jpeg",
      "/cars/nissannote3.jpeg",
      "/cars/nissannote4.jpeg",
      "/cars/nissannote5.jpeg",
      "/cars/nissannote6.jpeg",
      "/cars/nissannote7.jpeg",
      "/cars/nissannote8.jpeg",
      "/cars/nissannote9.jpeg",
      "/cars/nissannote10.jpeg",
      "/cars/nissannote11.jpeg",
      "/cars/nissannote12.jpeg",
      
    ],
  },

  {
    id: "2",
    name: "TOYOTA PRADO KBE",
    price: "880,000",
    imageUrl: "/cars/pradokbe.jpeg",
    altText: "Toyota Prado KBE",
    year: "2001",
    engine: "3000cc",
    mileage: "Medium Mileage",
    transmission: "Automatic",
    fuelType: "Diesel",
    linkSlug: "toyota-prado-kbe",
    description: "Rugged SUV built for adventure and off-road capabilities.",
    images: [
      "/cars/pradokbe.jpeg",
      "/cars/pradokbe1.jpeg",
      "/cars/pradokbe2.jpeg",
      "/cars/pradokbe3.jpeg",
      "/cars/pradokbe4.jpeg",
      "/cars/pradokbe5.jpeg",
      "/cars/pradokbe6.jpeg",
      "/cars/pradokbe7.jpeg",
      "/cars/pradokbe8.jpeg",
      "/cars/pradokbe9.jpeg",
      "/cars/pradokbe10.jpeg",
      "/cars/pradokbe11.jpeg",
      "/cars/pradokbe12.jpeg",
      "/cars/pradokbe13.jpeg",
      "/cars/pradokbe14.jpeg",
      "/cars/pradokbe15.jpeg", 

    ],
  },
  {
    id: "3",
    name: "NISSAN NV 350",
    price: "2.8M",
    imageUrl: "/cars/nv350.jpeg",
    altText: "Nissan NV 350",
    year: "2018",
    engine: "2500cc",
    mileage: "Low Mileage",
    transmission: "Manual",
    fuelType: "Diesel",
    linkSlug: "nv-350-2018",
    description: "Spacious commercial van ideal for business and cargo transport.",
    images: [
      "/cars/nv350.jpeg",
      "/cars/nv3501.jpeg",
      "/cars/nv3502.jpeg",
      "/cars/nv3503.jpeg",
      "/cars/nv3504.jpeg",
      "/cars/nv3505.jpeg",
      "/cars/nv3506.jpeg",
      "/cars/nv3507.jpeg",
      "/cars/nv3508.jpeg",
      "/cars/nv3509.jpeg",
      "/cars/nv35010.jpeg",
      "/cars/nv35011.jpeg",
      "/cars/nv35012.jpeg",
      "/cars/nv35013.jpeg",
      "/cars/nv35014.jpeg",
      "/cars/nv35015.jpeg",

      
    ],
  },
    {
    id: "1",
    name: "SUBARU IMPREZA",
    price: "1.25M",
    imageUrl: "/cars/white-subaru.jpeg",
    altText: "White Subaru Impreza",
    year: "2014",
    engine: "2000cc",
    mileage: "Low Mileage",
    transmission: "Automatic",
    fuelType: "Petrol",
    linkSlug: "subaru-impreza-2014",
    description: "Reliable AWD sedan with sporty performance and fuel efficiency.",
    images: [
      "/cars/white-subaru.jpeg",
      "/cars/subaru-impreza-interior.jpeg", // You'll need to add this image
      "/cars/subaru-impreza-rear.jpeg",     // You'll need to add this image
      "/cars/subaru-impreza-side.jpeg",     // You'll need to add this image
    ],
  },
  {
    id: "5",
    name: "Subaru Stella",
    price: "790,000(Negotiable)",
    imageUrl: "/cars/subarustella.jpeg",
    altText: "Subaru Stella",
    year: "2017",
    engine: "650cc",
    mileage: "Low Mileage",
    transmission: "Automatic",
    fuelType: "Petrol",
    linkSlug: "subaru-stella-2017",
    description: "Spacious and affordable family car ideal for city and long drives.",
    images: [
      "/cars/subarustella.jpeg",
      "/cars/subarustella1.jpeg",
      "/cars/subarustella2.jpeg",
      "/cars/subarustella3.jpeg", 
      "/cars/subarustella4.jpeg",
      "/cars/subarustella5.jpeg",
      "/cars/subarustella6.jpeg", 
      "/cars/subarustella7.jpeg",
      "/cars/subarustella8.jpeg",
      "/cars/subarustella9.jpeg", 
      "/cars/subarustella10.jpeg",
      "/cars/subarustella11.jpeg",
      "/cars/subarustella12.jpeg",
      
    
    ],
  },
  {
    id: "6",
    name: "TOYOTA VITZ",
    price: "1.28M",
    imageUrl: "/cars/vitz-blue.jpeg",
    altText: "Blue Toyota Vitz",
    year: "2018",
    engine: "1000cc",
    mileage: "Low Mileage",
    transmission: "Automatic",
    fuelType: "Petrol",
    linkSlug: "toyota-vitz-2018",
    description: "Compact and economical hatchback perfect for daily commuting.",
    images: [
      "/cars/vitz-blue.jpeg",
      "/cars/vitz-interior.jpeg",    // You'll need to add this image
      "/cars/vitz-rear.jpeg",        // You'll need to add this image
      "/cars/vitz-dashboard.jpeg",   // You'll need to add this image
    ],
  },
  {
    id: "7",
    name: "TOYOTA PRADO J120",
    price: "1.2M",
    imageUrl: "/cars/pradoj120.jpg",
    altText: "Toyota Prado J120",
    year: "2005",
    engine: "3500cc",
    mileage: "Low Mileage",
    transmission: "Automatic",
    fuelType: "Petrol",
    linkSlug: "toyota-prado-j120",
    description: "Rugged SUV built for adventure and family trips.",
    images: [
      "/cars/pradoj120.jpg",
      "/cars/pradoj1201.jpeg", // You'll need to add this image
      "/cars/pradoj1202.jpeg",     // You'll need to add this image
      "/cars/pradoj1203.jpeg", 
      "/cars/pradoj1204.jpeg",
      "/cars/pradoj1205.jpeg",
      "/cars/pradoj1206.jpeg",  
      "/cars/pradoj1207.jpeg", 
      "/cars/pradoj1208.jpeg",
      "/cars/pradoj1209.jpeg", 
      "/cars/pradoj12010.jpeg",
      "/cars/pradoj12011.jpeg",// You'll need to add this image
    ],
  },
  {
    id: "8",
    name: "MAZDA FLAIR",
    price: "700k",
    imageUrl: "/cars/mazdaflair.jpeg",
    altText: "Silver Mazda Flair ",
    year: "2016",
    engine: "650cc",
    mileage: "Low Mileage",
    transmission: "Automatic",
    fuelType: "Petrol",
    linkSlug: "mazda-flair-2016",
    description: "Fuel Efficient.Very clean and comfortable.",
    images: [
      "/cars/mazdaflair.jpeg",
      "/cars/mazdaflair1.jpeg",
      "/cars/mazdaflair2.jpeg",
      "/cars/mazdaflair3.jpeg",
      "/cars/mazdaflair4.jpeg",
      "/cars/mazdaflair5.jpeg",
      "/cars/mazdaflair6.jpeg",
      "/cars/mazdaflair7.jpeg",
      "/cars/mazdaflair8.jpeg",
      "/cars/mazdaflair9.jpeg",
      "/cars/mazdaflair10.jpeg",
      "/cars/mazdaflair11.jpeg",
      "/cars/mazdaflair12.jpeg",
      "/cars/mazdaflair13.jpeg",
      "/cars/mazdaflair14.jpeg",
      "/cars/mazdaflair15.jpeg",

    ],
  },
  
  {
    id: "9",
    name: "Nissan NV200",
    price: "500K",
    imageUrl: "/cars/nv200.jpeg",
    altText: "Black Nissan NV200",
    year: "2014",
    engine: "1500cc",
    mileage: "Medium Mileage",
    transmission: "CVT",
    fuelType: "Petrol",
    linkSlug: "nissan-nv200-2014",
    description: "💨 Smooth Drive | 🧳 Spacious & Practical | ⛽ Super Fuel Efficient | ❄️ Functional AC.",
    images: [
      "/cars/nv200.jpeg",
      "/cars/nv2001.jpeg",
      "/cars/nv2002.jpeg",
      "/cars/nv2003.jpeg",
      "/cars/nv2004.jpeg",
      "/cars/nv2005.jpeg",
      "/cars/nv2006.jpeg",
      "/cars/nv2007.jpeg",
      "/cars/nv2008.jpeg",
      "/cars/nv2009.jpeg",
      "/cars/nv20010.jpeg",
      "/cars/nv20011.jpeg",
      "/cars/nv20012.jpeg",
      "/cars/nv20013.jpeg",
         // You'll need to add this image
    ],
  },
  {
    id: "10",
    name: "Honda Fit Hybrid",
    price: "650k",
    imageUrl: "/cars/hondafit15.jpeg",
    altText: "White Honda Fit Hybrid",
    year: "2012",
    engine: "1300cc (Hybrid)",
    mileage: "Medium Mileage",
    transmission: "Automatic",
    fuelType: "Petrol",
    linkSlug: "honda-fit-hybrid-2012",
    description: "Compact, stylish and reliable. Clean Inside out. Perfect for city and long drives.",
    images: [
      "/cars/hondafit14.jpeg",
      "/cars/hondafit1.jpeg",
      "/cars/hondafit2.jpeg",
      "/cars/hondafit3.jpeg",
      "/cars/hondafit4.jpeg",
      "/cars/hondafit5.jpeg",
      "/cars/hondafit6.jpeg",
      "/cars/hondafit7.jpeg",
      "/cars/hondafit8.jpeg",
      "/cars/hondafit9.jpeg",
      "/cars/hondafit10.jpeg",
      "/cars/hondafit11.jpeg",
      "/cars/hondafit12.jpeg",
      "/cars/hondafit13.jpeg",
      "/cars/hondafit14.jpeg",
      "/cars/hondafit15.jpeg",
      "/cars/hondafit16.jpeg",

     
    ],
  },
  {
    id: "11",
    name: "Toyota Hiace Ambulance",
    price: "5.1M",
    imageUrl: "/cars/ambulance.jpeg",
    altText: "Silver Toyota Hiace Ambulance",
    year: "2016",
    engine: "2700cc",
    mileage: "83,000 Km",
    transmission: "Automatic",
    fuelType: "Petrol",
    linkSlug: "toyota-hiace-ambulance-2016",
    description: "🩺 High Roof (9L) | Fully Functional | Ready for Emergency Response 🚨",
    images: [
      "/cars/ambulance.jpeg",
      "/cars/ambulance1.jpeg",
      "/cars/ambulance2.jpeg",
      "/cars/ambulance3.jpeg",
      "/cars/ambulance4.jpeg",
      "/cars/ambulance5.jpeg",
      "/cars/ambulance6.jpeg",
      "/cars/ambulance7.jpeg",
      "/cars/ambulance8.jpeg",
      "/cars/ambulance9.jpeg",
      "/cars/ambulance10.jpeg",
      "/cars/ambulance11.jpeg",
      "/cars/ambulance12.jpeg",
      "/cars/ambulance13.jpeg",

    ],
  },
  {
    id: "12",
    name: "Daihatsu Mira",
    price: "Price drop from 650k to550k",
    imageUrl: "/cars/daihatsumira.jpeg",
    altText: "White Daihatsu Mira",
    year: "2017",
    engine: "650cc",
    transmission: "Automatic",
    fuelType: "Petrol",
    linkSlug: "daihatsu-mira-2017",
    description: "Clean Inside out. Price is negotiable.Cars are a necessity❤️.",
    images: [
      "/cars/daihatsumira.jpeg",
      "/cars/daihatsumira1.jpeg",
      "/cars/daihatsumira2.jpeg",
      "/cars/daihatsumira3.jpeg",
      "/cars/daihatsumira4.jpeg",
      "/cars/daihatsumira5.jpeg",
      "/cars/daihatsumira6.jpeg",
      "/cars/daihatsumira7.jpeg",
      "/cars/daihatsumira8.jpeg",
      "/cars/daihatsumira9.jpeg",
      "/cars/daihatsumira10.jpeg",

     
    ],
  },
   {
    id: "13",
    name: "Toyota Coaster",
    price: "2.4M",
    imageUrl: "/cars/toyotacoaster.jpeg",
    altText: "White Toyota Coaster",
    engine: "2700cc",
    transmission: "Manual",
    fuelType: "Diesel",
    linkSlug: "toyota-coaster-2017",
    description: "Compact, stylish and reliable. By and drive. Perfect for Schools, company, tour. Ready to work. Clean Inside out. Perfect for business",
    images: [
      "/cars/toyotacoaster.jpeg",
      "/cars/toyotacoaster1.jpeg",
      "/cars/toyotacoaster2.jpeg",
      "/cars/toyotacoaster3.jpeg",
      "/cars/toyotacoaster4.jpeg",
      "/cars/toyotacoaster5.jpeg",
      "/cars/toyotacoaster6.jpeg",
     
    ],
  },
  
   {
    id: "14",
    name: "Mazda Demio",
    price: "850k",
    imageUrl: "/cars/mazdademio.jpeg",
    altText: "Blue Mazda Demio",
    engine: "1300cc",
    year: "2015",
    transmission: "Automatic",
    fuelType: "Petrol",
    linkSlug: "mazda-demio-2015",
    description: "Comfortable, Stylish and reliable. Clean interior and exterior With a rear camera",
    images: [
      "/cars/mazdademio.jpeg",
      "/cars/mazdademio1.jpeg",
      "/cars/mazdademio2.jpeg",
      "/cars/mazdademio3.jpeg",
      "/cars/mazdademio4.jpeg",
      "/cars/mazdademio5.jpeg",
      "/cars/mazdademio6.jpeg",
      "/cars/mazdademio7.jpeg",
      "/cars/mazdademio8.jpeg",
      "/cars/mazdademio9.jpeg",
      "/cars/mazdademio10.jpeg",
      "/cars/mazdademio11.jpeg",
      "/cars/mazdademio12.jpeg",
      "/cars/mazdademio13.jpeg",
      "/cars/mazdademio14.jpeg",
      "/cars/mazdademio15.jpeg",
      "/cars/mazdademio16.jpeg",

    ],
  },
  
];

export const metadata = {
  title: "Segen Motors - Available Inventory",
  description: "Explore our wide selection of quality used cars for sale.",
};


export default function InventoryPage() {
  return (
    <div className="py-8">
      <h1 className="text-4xl font-bold text-center mb-10">Our Available Vehicles 🚗</h1>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
        {cars.map((car) => (
          <CarCard key={car.id} car={car} />
        ))}
      </div>
    </div>
  );
}